In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("newDF.csv")
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,10689.0,Generator Rex: Agent of Providence,3DS,2011.0,Action,Activision,0.07,0.02,0.00,0.01,0.10
1,10856.0,Bleach,DS,2008.0,Sports,Electronic Arts,0.07,0.02,0.00,0.01,0.09
2,12101.0,Family Trainer: Treasure Adventure,Wii,2010.0,Sports,Namco Bandai Games,0.00,0.06,0.00,0.01,0.07
3,2973.0,Shark Tale,GBA,2004.0,Action,Activision,0.49,0.18,0.00,0.01,0.68
4,8504.0,Medieval Games,Wii,2009.0,Action,Vir2L Studios,0.14,0.01,0.00,0.01,0.16
...,...,...,...,...,...,...,...,...,...,...,...
548,1004.0,Star Wars: Starfighter,PS2,2001.0,Simulation,Activision,0.61,0.87,0.02,0.26,1.76
549,15227.0,Umineko no Naku Koro ni: Majo to Suiri no Rinb...,PS3,2010.0,Adventure,Alchemist,0.00,0.00,0.02,0.00,0.02
550,15993.0,Shinseiki Evangelion: Battle Orchestra Portable,PSP,2009.0,Fighting,Broccoli,0.00,0.00,0.01,0.00,0.01
551,5753.0,Cabela's Outdoor Adventures (2009),Wii,2009.0,Sports,Activision Value,0.29,0.00,0.00,0.02,0.31
552,15887.0,GTI Club: Supermini Festa!,Wii,2010.0,Racing,Konami Digital Entertainment,0.01,0.00,0.00,0.00,0.02

In [7]:
df = df.drop(columns="Rank")
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Generator Rex: Agent of Providence,3DS,2011.0,Action,Activision,0.07,0.02,0.00,0.01,0.10
1,Bleach,DS,2008.0,Sports,Electronic Arts,0.07,0.02,0.00,0.01,0.09
2,Family Trainer: Treasure Adventure,Wii,2010.0,Sports,Namco Bandai Games,0.00,0.06,0.00,0.01,0.07
3,Shark Tale,GBA,2004.0,Action,Activision,0.49,0.18,0.00,0.01,0.68
4,Medieval Games,Wii,2009.0,Action,Vir2L Studios,0.14,0.01,0.00,0.01,0.16
...,...,...,...,...,...,...,...,...,...,...
548,Star Wars: Starfighter,PS2,2001.0,Simulation,Activision,0.61,0.87,0.02,0.26,1.76
549,Umineko no Naku Koro ni: Majo to Suiri no Rinb...,PS3,2010.0,Adventure,Alchemist,0.00,0.00,0.02,0.00,0.02
550,Shinseiki Evangelion: Battle Orchestra Portable,PSP,2009.0,Fighting,Broccoli,0.00,0.00,0.01,0.00,0.01
551,Cabela's Outdoor Adventures (2009),Wii,2009.0,Sports,Activision Value,0.29,0.00,0.00,0.02,0.31
552,GTI Club: Supermini Festa!,Wii,2010.0,Racing,Konami Digital Entertainment,0.01,0.00,0.00,0.00,0.02

In [40]:
#- Продемонстрировать работу OrdinalEncoder и использовать его на датасете;
from sklearn.preprocessing import OrdinalEncoder

Onec = OrdinalEncoder()
Onec.fit(df[['Genre','EU_Sales','Other_Sales','Global_Sales']])
df

,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Generator Rex: Agent of Providence,2011.0,0,Activision,0.034979,0.999388,0.00,1.0,9.0
1,Bleach,2008.0,10,Electronic Arts,0.034979,0.999388,0.00,1.0,8.0
2,Family Trainer: Treasure Adventure,2010.0,10,Namco Bandai Games,0.000000,1.000000,0.00,1.0,6.0
3,Shark Tale,2004.0,0,Activision,0.027212,0.999630,0.00,1.0,61.0
4,Medieval Games,2009.0,0,Vir2L Studios,0.138648,0.990342,0.00,1.0,15.0
...,...,...,...,...,...,...,...,...,...
548,Star Wars: Starfighter,2001.0,9,Activision,0.010701,0.999943,0.02,25.0,110.0
549,Umineko no Naku Koro ni: Majo to Suiri no Rinb...,2010.0,1,Alchemist,0.000000,0.000000,0.02,0.0,1.0
550,Shinseiki Evangelion: Battle Orchestra Portable,2009.0,2,Broccoli,0.000000,0.000000,0.01,0.0,0.0
551,Cabela's Outdoor Adventures (2009),2009.0,10,Activision Value,1.000000,0.000000,0.00,2.0,30.0
552,GTI Club: Supermini Festa!,2010.0,6,Konami Digital Entertainment,1.000000,0.000000,0.00,0.0,1.0

In [9]:
Onec.categories_

[array(['2600', '3DS', 'DC', 'DS', 'GB', 'GBA', 'GC', 'GEN', 'N64', 'NES',
        'PC', 'PS', 'PS2', 'PS3', 'PS4', 'PSP', 'PSV', 'SAT', 'SNES',
        'Wii', 'WiiU', 'X360', 'XB', 'XOne'], dtype=object),
 array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
        0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
        0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.3 , 0.31, 0.32, 0.33,
        0.34, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44, 0.48, 0.49,
        0.51, 0.52, 0.53, 0.54, 0.58, 0.59, 0.63, 0.64, 0.67, 0.72, 0.76,
        0.78, 0.86, 0.87, 0.9 , 0.91, 0.94, 0.96, 1.  , 1.07, 1.09, 1.12,
        1.18, 1.28, 1.41, 1.62, 2.23, 2.8 , 3.69, 8.03]),
 array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
        0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.2 , 0.21, 0.22,
        0.23, 0.24, 0.25, 0.26, 0.28, 0.33, 0.34, 0.35, 0.36, 0.38, 0.39,
        0.41, 0.44, 0.45, 0.46, 0.48, 0.49, 0.8 , 1.63, 2.15]),
 array([1.000e-02, 2.000e-02, 3.000e-02, 4.000e-02, 5.000e-02, 6.000e-02,
        7.000e-02, 8.000e-02, 9.000e-02, 1.000e-01, 1.100e-01, 1.200e-01,
        1.300e-01, 1.400e-01, 1.500e-01, 1.600e-01, 1.700e-01, 1.800e-01,
        1.900e-01, 2.000e-01, 2.100e-01, 2.200e-01, 2.300e-01, 2.400e-01,
        2.500e-01, 2.600e-01, 2.700e-01, 2.800e-01, 2.900e-01, 3.000e-01,
        3.100e-01, 3.200e-01, 3.300e-01, 3.400e-01, 3.500e-01, 3.600e-01,
        3.700e-01, 3.800e-01, 4.000e-01, 4.100e-01, 4.200e-01, 4.300e-01,
        4.400e-01, 4.500e-01, 4.700e-01, 4.800e-01, 4.900e-01, 5.000e-01,
        5.100e-01, 5.200e-01, 5.300e-01, 5.400e-01, 5.600e-01, 5.800e-01,
        6.000e-01, 6.200e-01, 6.300e-01, 6.400e-01, 6.500e-01, 6.600e-01,
        6.700e-01, 6.800e-01, 6.900e-01, 7.100e-01, 7.200e-01, 7.400e-01,
        7.600e-01, 7.700e-01, 7.900e-01, 8.100e-01, 8.300e-01, 8.500e-01,
        8.600e-01, 8.700e-01, 9.000e-01, 9.300e-01, 9.500e-01, 9.600e-01,
        9.800e-01, 9.900e-01, 1.000e+00, 1.030e+00, 1.050e+00, 1.060e+00,
        1.070e+00, 1.080e+00, 1.090e+00, 1.100e+00, 1.110e+00, 1.150e+00,
        1.210e+00, 1.240e+00, 1.250e+00, 1.310e+00, 1.330e+00, 1.350e+00,
        1.430e+00, 1.450e+00, 1.460e+00, 1.470e+00, 1.500e+00, 1.520e+00,
        1.550e+00, 1.600e+00, 1.610e+00, 1.640e+00, 1.670e+00, 1.690e+00,
        1.730e+00, 1.740e+00, 1.760e+00, 1.770e+00, 1.780e+00, 1.810e+00,
        1.940e+00, 1.980e+00, 2.080e+00, 2.140e+00, 2.180e+00, 2.190e+00,
        2.230e+00, 2.280e+00, 2.310e+00, 2.380e+00, 2.410e+00, 2.520e+00,
        2.560e+00, 2.640e+00, 2.720e+00, 2.890e+00, 2.900e+00, 3.120e+00,
        3.280e+00, 3.670e+00, 3.830e+00, 4.060e+00, 4.340e+00, 4.680e+00,
        5.130e+00, 6.240e+00, 6.270e+00, 1.069e+01, 2.272e+01])]

In [10]:
Onec = OrdinalEncoder()
df[['Platform','EU_Sales','Other_Sales','Global_Sales']] = Onec.fit_transform(df[['Platform','EU_Sales','Other_Sales','Global_Sales']])
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Generator Rex: Agent of Providence,1.0,2011.0,Action,Activision,0.07,2.0,0.00,1.0,9.0
1,Bleach,3.0,2008.0,Sports,Electronic Arts,0.07,2.0,0.00,1.0,8.0
2,Family Trainer: Treasure Adventure,19.0,2010.0,Sports,Namco Bandai Games,0.00,6.0,0.00,1.0,6.0
3,Shark Tale,5.0,2004.0,Action,Activision,0.49,18.0,0.00,1.0,61.0
4,Medieval Games,19.0,2009.0,Action,Vir2L Studios,0.14,1.0,0.00,1.0,15.0
...,...,...,...,...,...,...,...,...,...,...
548,Star Wars: Starfighter,12.0,2001.0,Simulation,Activision,0.61,57.0,0.02,25.0,110.0
549,Umineko no Naku Koro ni: Majo to Suiri no Rinb...,13.0,2010.0,Adventure,Alchemist,0.00,0.0,0.02,0.0,1.0
550,Shinseiki Evangelion: Battle Orchestra Portable,15.0,2009.0,Fighting,Broccoli,0.00,0.0,0.01,0.0,0.0
551,Cabela's Outdoor Adventures (2009),19.0,2009.0,Sports,Activision Value,0.29,0.0,0.00,2.0,30.0
552,GTI Club: Supermini Festa!,19.0,2010.0,Racing,Konami Digital Entertainment,0.01,0.0,0.00,0.0,1.0

In [12]:
#- Обязательно преобразовать 1 категориальный признак с помощью LabelEncoder;
from sklearn.preprocessing import LabelEncoder

Lenc = LabelEncoder()
Lenc.fit(df['Genre'])

df['Genre'] = Lenc.fit_transform(df['Genre'])

df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Generator Rex: Agent of Providence,1.0,2011.0,0,Activision,0.07,2.0,0.00,1.0,9.0
1,Bleach,3.0,2008.0,10,Electronic Arts,0.07,2.0,0.00,1.0,8.0
2,Family Trainer: Treasure Adventure,19.0,2010.0,10,Namco Bandai Games,0.00,6.0,0.00,1.0,6.0
3,Shark Tale,5.0,2004.0,0,Activision,0.49,18.0,0.00,1.0,61.0
4,Medieval Games,19.0,2009.0,0,Vir2L Studios,0.14,1.0,0.00,1.0,15.0
...,...,...,...,...,...,...,...,...,...,...
548,Star Wars: Starfighter,12.0,2001.0,9,Activision,0.61,57.0,0.02,25.0,110.0
549,Umineko no Naku Koro ni: Majo to Suiri no Rinb...,13.0,2010.0,1,Alchemist,0.00,0.0,0.02,0.0,1.0
550,Shinseiki Evangelion: Battle Orchestra Portable,15.0,2009.0,2,Broccoli,0.00,0.0,0.01,0.0,0.0
551,Cabela's Outdoor Adventures (2009),19.0,2009.0,10,Activision Value,0.29,0.0,0.00,2.0,30.0
552,GTI Club: Supermini Festa!,19.0,2010.0,6,Konami Digital Entertainment,0.01,0.0,0.00,0.0,1.0

In [13]:
Lenc.classes_

array(['Action', 'Adventure', 'Fighting', 'Misc', 'Platform', 'Puzzle',
       'Racing', 'Role-Playing', 'Shooter', 'Simulation', 'Sports',
       'Strategy'], dtype=object)

In [17]:
#- Показать пример выполнения OneHotEncoder (использовать его на датасете не обязательно);
from sklearn.preprocessing import OneHotEncoder

OneHot = OneHotEncoder()
OneHot.fit(df[['Genre']])

df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Generator Rex: Agent of Providence,1.0,2011.0,0,Activision,0.07,2.0,0.00,1.0,9.0
1,Bleach,3.0,2008.0,10,Electronic Arts,0.07,2.0,0.00,1.0,8.0
2,Family Trainer: Treasure Adventure,19.0,2010.0,10,Namco Bandai Games,0.00,6.0,0.00,1.0,6.0
3,Shark Tale,5.0,2004.0,0,Activision,0.49,18.0,0.00,1.0,61.0
4,Medieval Games,19.0,2009.0,0,Vir2L Studios,0.14,1.0,0.00,1.0,15.0
...,...,...,...,...,...,...,...,...,...,...
548,Star Wars: Starfighter,12.0,2001.0,9,Activision,0.61,57.0,0.02,25.0,110.0
549,Umineko no Naku Koro ni: Majo to Suiri no Rinb...,13.0,2010.0,1,Alchemist,0.00,0.0,0.02,0.0,1.0
550,Shinseiki Evangelion: Battle Orchestra Portable,15.0,2009.0,2,Broccoli,0.00,0.0,0.01,0.0,0.0
551,Cabela's Outdoor Adventures (2009),19.0,2009.0,10,Activision Value,0.29,0.0,0.00,2.0,30.0
552,GTI Club: Supermini Festa!,19.0,2010.0,6,Konami Digital Entertainment,0.01,0.0,0.00,0.0,1.0

In [15]:
Onec.categories_

[array(['2600', '3DS', 'DC', 'DS', 'GB', 'GBA', 'GC', 'GEN', 'N64', 'NES',
        'PC', 'PS', 'PS2', 'PS3', 'PS4', 'PSP', 'PSV', 'SAT', 'SNES',
        'Wii', 'WiiU', 'X360', 'XB', 'XOne'], dtype=object),
 array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
        0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
        0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.3 , 0.31, 0.32, 0.33,
        0.34, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44, 0.48, 0.49,
        0.51, 0.52, 0.53, 0.54, 0.58, 0.59, 0.63, 0.64, 0.67, 0.72, 0.76,
        0.78, 0.86, 0.87, 0.9 , 0.91, 0.94, 0.96, 1.  , 1.07, 1.09, 1.12,
        1.18, 1.28, 1.41, 1.62, 2.23, 2.8 , 3.69, 8.03]),
 array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
        0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.2 , 0.21, 0.22,
        0.23, 0.24, 0.25, 0.26, 0.28, 0.33, 0.34, 0.35, 0.36, 0.38, 0.39,
        0.41, 0.44, 0.45, 0.46, 0.48, 0.49, 0.8 , 1.63, 2.15]),
 array([1.000e-02, 2.000e-02, 3.000e-02, 4.000e-02, 5.000e-02, 6.000e-02,
        7.000e-02, 8.000e-02, 9.000e-02, 1.000e-01, 1.100e-01, 1.200e-01,
        1.300e-01, 1.400e-01, 1.500e-01, 1.600e-01, 1.700e-01, 1.800e-01,
        1.900e-01, 2.000e-01, 2.100e-01, 2.200e-01, 2.300e-01, 2.400e-01,
        2.500e-01, 2.600e-01, 2.700e-01, 2.800e-01, 2.900e-01, 3.000e-01,
        3.100e-01, 3.200e-01, 3.300e-01, 3.400e-01, 3.500e-01, 3.600e-01,
        3.700e-01, 3.800e-01, 4.000e-01, 4.100e-01, 4.200e-01, 4.300e-01,
        4.400e-01, 4.500e-01, 4.700e-01, 4.800e-01, 4.900e-01, 5.000e-01,
        5.100e-01, 5.200e-01, 5.300e-01, 5.400e-01, 5.600e-01, 5.800e-01,
        6.000e-01, 6.200e-01, 6.300e-01, 6.400e-01, 6.500e-01, 6.600e-01,
        6.700e-01, 6.800e-01, 6.900e-01, 7.100e-01, 7.200e-01, 7.400e-01,
        7.600e-01, 7.700e-01, 7.900e-01, 8.100e-01, 8.300e-01, 8.500e-01,
        8.600e-01, 8.700e-01, 9.000e-01, 9.300e-01, 9.500e-01, 9.600e-01,
        9.800e-01, 9.900e-01, 1.000e+00, 1.030e+00, 1.050e+00, 1.060e+00,
        1.070e+00, 1.080e+00, 1.090e+00, 1.100e+00, 1.110e+00, 1.150e+00,
        1.210e+00, 1.240e+00, 1.250e+00, 1.310e+00, 1.330e+00, 1.350e+00,
        1.430e+00, 1.450e+00, 1.460e+00, 1.470e+00, 1.500e+00, 1.520e+00,
        1.550e+00, 1.600e+00, 1.610e+00, 1.640e+00, 1.670e+00, 1.690e+00,
        1.730e+00, 1.740e+00, 1.760e+00, 1.770e+00, 1.780e+00, 1.810e+00,
        1.940e+00, 1.980e+00, 2.080e+00, 2.140e+00, 2.180e+00, 2.190e+00,
        2.230e+00, 2.280e+00, 2.310e+00, 2.380e+00, 2.410e+00, 2.520e+00,
        2.560e+00, 2.640e+00, 2.720e+00, 2.890e+00, 2.900e+00, 3.120e+00,
        3.280e+00, 3.670e+00, 3.830e+00, 4.060e+00, 4.340e+00, 4.680e+00,
        5.130e+00, 6.240e+00, 6.270e+00, 1.069e+01, 2.272e+01])]

In [16]:
Onec = OrdinalEncoder()
df[['Platform','EU_Sales','Other_Sales','Global_Sales']] = Onec.fit_transform(df[['Platform','EU_Sales','Other_Sales','Global_Sales']])
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Generator Rex: Agent of Providence,1.0,2011.0,0,Activision,0.07,2.0,0.00,1.0,9.0
1,Bleach,3.0,2008.0,10,Electronic Arts,0.07,2.0,0.00,1.0,8.0
2,Family Trainer: Treasure Adventure,19.0,2010.0,10,Namco Bandai Games,0.00,6.0,0.00,1.0,6.0
3,Shark Tale,5.0,2004.0,0,Activision,0.49,18.0,0.00,1.0,61.0
4,Medieval Games,19.0,2009.0,0,Vir2L Studios,0.14,1.0,0.00,1.0,15.0
...,...,...,...,...,...,...,...,...,...,...
548,Star Wars: Starfighter,12.0,2001.0,9,Activision,0.61,57.0,0.02,25.0,110.0
549,Umineko no Naku Koro ni: Majo to Suiri no Rinb...,13.0,2010.0,1,Alchemist,0.00,0.0,0.02,0.0,1.0
550,Shinseiki Evangelion: Battle Orchestra Portable,15.0,2009.0,2,Broccoli,0.00,0.0,0.01,0.0,0.0
551,Cabela's Outdoor Adventures (2009),19.0,2009.0,10,Activision Value,0.29,0.0,0.00,2.0,30.0
552,GTI Club: Supermini Festa!,19.0,2010.0,6,Konami Digital Entertainment,0.01,0.0,0.00,0.0,1.0

In [18]:
#- Провести нормализацию с помощью Normalize на числовых признаках;
from sklearn.preprocessing import LabelEncoder

Lenc = LabelEncoder()
Lenc.fit(df['Genre'])

df['Genre'] = Lenc.fit_transform(df['Genre'])

df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Generator Rex: Agent of Providence,1.0,2011.0,0,Activision,0.07,2.0,0.00,1.0,9.0
1,Bleach,3.0,2008.0,10,Electronic Arts,0.07,2.0,0.00,1.0,8.0
2,Family Trainer: Treasure Adventure,19.0,2010.0,10,Namco Bandai Games,0.00,6.0,0.00,1.0,6.0
3,Shark Tale,5.0,2004.0,0,Activision,0.49,18.0,0.00,1.0,61.0
4,Medieval Games,19.0,2009.0,0,Vir2L Studios,0.14,1.0,0.00,1.0,15.0
...,...,...,...,...,...,...,...,...,...,...
548,Star Wars: Starfighter,12.0,2001.0,9,Activision,0.61,57.0,0.02,25.0,110.0
549,Umineko no Naku Koro ni: Majo to Suiri no Rinb...,13.0,2010.0,1,Alchemist,0.00,0.0,0.02,0.0,1.0
550,Shinseiki Evangelion: Battle Orchestra Portable,15.0,2009.0,2,Broccoli,0.00,0.0,0.01,0.0,0.0
551,Cabela's Outdoor Adventures (2009),19.0,2009.0,10,Activision Value,0.29,0.0,0.00,2.0,30.0
552,GTI Club: Supermini Festa!,19.0,2010.0,6,Konami Digital Entertainment,0.01,0.0,0.00,0.0,1.0

In [19]:
Lenc.classes_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
from sklearn.preprocessing import OneHotEncoder

OneHot = OneHotEncoder()
OneHot.fit(df[['Platform']])

df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Generator Rex: Agent of Providence,1.0,2011.0,0,Activision,0.07,2.0,0.00,1.0,9.0
1,Bleach,3.0,2008.0,10,Electronic Arts,0.07,2.0,0.00,1.0,8.0
2,Family Trainer: Treasure Adventure,19.0,2010.0,10,Namco Bandai Games,0.00,6.0,0.00,1.0,6.0
3,Shark Tale,5.0,2004.0,0,Activision,0.49,18.0,0.00,1.0,61.0
4,Medieval Games,19.0,2009.0,0,Vir2L Studios,0.14,1.0,0.00,1.0,15.0
...,...,...,...,...,...,...,...,...,...,...
548,Star Wars: Starfighter,12.0,2001.0,9,Activision,0.61,57.0,0.02,25.0,110.0
549,Umineko no Naku Koro ni: Majo to Suiri no Rinb...,13.0,2010.0,1,Alchemist,0.00,0.0,0.02,0.0,1.0
550,Shinseiki Evangelion: Battle Orchestra Portable,15.0,2009.0,2,Broccoli,0.00,0.0,0.01,0.0,0.0
551,Cabela's Outdoor Adventures (2009),19.0,2009.0,10,Activision Value,0.29,0.0,0.00,2.0,30.0
552,GTI Club: Supermini Festa!,19.0,2010.0,6,Konami Digital Entertainment,0.01,0.0,0.00,0.0,1.0

In [21]:
OneHot.categories_

[array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])]

In [22]:
OneHot.transform(df[['Platform']]).toarray()

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
df = df.drop(columns="Platform")
df

,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Generator Rex: Agent of Providence,2011.0,0,Activision,0.07,2.0,0.00,1.0,9.0
1,Bleach,2008.0,10,Electronic Arts,0.07,2.0,0.00,1.0,8.0
2,Family Trainer: Treasure Adventure,2010.0,10,Namco Bandai Games,0.00,6.0,0.00,1.0,6.0
3,Shark Tale,2004.0,0,Activision,0.49,18.0,0.00,1.0,61.0
4,Medieval Games,2009.0,0,Vir2L Studios,0.14,1.0,0.00,1.0,15.0
...,...,...,...,...,...,...,...,...,...
548,Star Wars: Starfighter,2001.0,9,Activision,0.61,57.0,0.02,25.0,110.0
549,Umineko no Naku Koro ni: Majo to Suiri no Rinb...,2010.0,1,Alchemist,0.00,0.0,0.02,0.0,1.0
550,Shinseiki Evangelion: Battle Orchestra Portable,2009.0,2,Broccoli,0.00,0.0,0.01,0.0,0.0
551,Cabela's Outdoor Adventures (2009),2009.0,10,Activision Value,0.29,0.0,0.00,2.0,30.0
552,GTI Club: Supermini Festa!,2010.0,6,Konami Digital Entertainment,0.01,0.0,0.00,0.0,1.0

In [24]:
from sklearn.preprocessing import Normalizer

Norm = Normalizer()

df[['NA_Sales','EU_Sales']] = Norm.fit_transform(df[['NA_Sales','EU_Sales']])
df

,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Generator Rex: Agent of Providence,2011.0,0,Activision,0.034979,0.999388,0.00,1.0,9.0
1,Bleach,2008.0,10,Electronic Arts,0.034979,0.999388,0.00,1.0,8.0
2,Family Trainer: Treasure Adventure,2010.0,10,Namco Bandai Games,0.000000,1.000000,0.00,1.0,6.0
3,Shark Tale,2004.0,0,Activision,0.027212,0.999630,0.00,1.0,61.0
4,Medieval Games,2009.0,0,Vir2L Studios,0.138648,0.990342,0.00,1.0,15.0
...,...,...,...,...,...,...,...,...,...
548,Star Wars: Starfighter,2001.0,9,Activision,0.010701,0.999943,0.02,25.0,110.0
549,Umineko no Naku Koro ni: Majo to Suiri no Rinb...,2010.0,1,Alchemist,0.000000,0.000000,0.02,0.0,1.0
550,Shinseiki Evangelion: Battle Orchestra Portable,2009.0,2,Broccoli,0.000000,0.000000,0.01,0.0,0.0
551,Cabela's Outdoor Adventures (2009),2009.0,10,Activision Value,1.000000,0.000000,0.00,2.0,30.0
552,GTI Club: Supermini Festa!,2010.0,6,Konami Digital Entertainment,1.000000,0.000000,0.00,0.0,1.0

In [31]:
#- Разделить датасет на обучающую и тестовую выборку.
from sklearn.model_selection import train_test_split

Y = df['Publisher']
X = df.drop(columns="Publisher")

x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [32]:
x_train

,Name,Year,Genre,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
18,Cabela's Big Game Hunter 2010,2009.0,10,1.000000,0.000000,0.00,3.0,38.0
325,Shinobi Koutsutsu,2014.0,1,0.000000,0.000000,0.01,0.0,0.0
486,I-Ninja,2003.0,4,0.024992,0.999688,0.00,0.0,6.0
296,The 3rd Birthday,2010.0,7,0.018568,0.999828,0.27,5.0,48.0
478,LEGO Star Wars: The Complete Saga,2007.0,0,0.026832,0.999640,0.00,23.0,127.0
...,...,...,...,...,...,...,...,...
71,Metal Max Returns,1995.0,7,0.000000,0.000000,0.04,0.0,3.0
106,MySims Party,2009.0,9,0.059892,0.998205,0.00,2.0,22.0
270,The Penguins of Madagascar,2010.0,0,0.010833,0.999941,0.00,2.0,26.0
435,Sesame Street: Elmo's Letter Adventure,1999.0,3,0.034979,0.999388,0.00,0.0,17.0
102,Puyo Puyo!! 20th Anniversary,2011.0,5,0.000000,0.000000,0.14,0.0,13.0

In [33]:
x_test

,Name,Year,Genre,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
548,Star Wars: Starfighter,2001.0,9,0.010701,0.999943,0.02,25.0,110.0
82,Toukiden Kiwami,2015.0,0,0.007143,0.999974,0.02,2.0,16.0
523,Brothers Conflict: Passion Pink,2012.0,0,0.000000,0.000000,0.03,0.0,2.0
332,Summer Athletics: The Ultimate Challenge,2008.0,10,0.000000,0.000000,0.00,18.0,17.0
132,"Hanayaka Kana, Ware ga Ichizoku Twin Pack",2011.0,3,0.000000,0.000000,0.03,0.0,2.0
...,...,...,...,...,...,...,...,...
140,CSI: Dark Motives,2007.0,1,0.049938,0.998752,0.00,1.0,6.0
149,Samurai Warriors: Xtreme Legends,2004.0,0,0.013332,0.999911,0.36,1.0,43.0
498,Vanquish,2010.0,8,0.009545,0.999954,0.11,9.0,55.0
153,Dragon Quest Monsters 2,2014.0,7,0.000000,0.000000,0.79,0.0,68.0
172,Alleyway,1989.0,5,0.027418,0.999624,0.55,5.0,114.0

In [34]:
y_train

18       Activision Value
325          Idea Factory
486    Namco Bandai Games
296           Square Enix
478             LucasArts
              ...
71              Data East
106       Electronic Arts
270                   THQ
435              NewKidCo
102                  Sega
Name: Publisher, Length: 442, dtype: object

In [35]:
y_test

548           Activision
82            Tecmo Koei
523         Idea Factory
332    DTP Entertainment
132         Idea Factory
             ...
140              Ubisoft
149           Tecmo Koei
498                 Sega
153          Square Enix
172             Nintendo
Name: Publisher, Length: 111, dtype: object